// Generated by CoffeeScript 1.7.1
(function() {
  window.JiraStoryTime = window.JiraStoryTime || {};

  window.JiraStoryTime.DragController = {
    handleDragStart: function(e) {
      this.style.opacity = "0.4";
      return e.dataTransfer.setData("storyId", $(e.target).closest(".story")[0].getAttribute("id"));
    },
    handleDragOver: function(e) {
      if (e.preventDefault) {
        e.preventDefault();
      }
      return false;
    },
    handleDragEnter: function(e) {
      this.classList.add("over");
      return $(this).find(".story_board_row_drop_mask").show();
    },
    handleDragLeave: function(e) {
      e.stopPropagation();
      e.preventDefault();
      $(this.parentElement).removeClass("over");
      return $(this).hide();
    },
    handleDrop: function(e) {
      var newPoints;
      if (e.stopPropagation) {
        e.stopPropagation();
      }
      newPoints = this.parentElement.getAttribute("data-story-points");
      $("#" + e.dataTransfer.getData("storyId")).trigger("pointsChanged", [newPoints]);
      $(e.target).hide();
      return false;
    },
    handleDragEnd: function(e) {
      return [].forEach.call(window.JiraStoryTime.DragController.cols, function(col) {
        col.style.opacity = "1";
        return col.classList.remove("over");
      });
    },
    setup: function() {
      var _this;
      this.cols = document.querySelectorAll("#story_board .story_board_row");
      _this = this;
      return [].forEach.call(this.cols, function(col) {
        col.addEventListener("dragstart", _this.handleDragStart, false);
        col.addEventListener("dragenter", _this.handleDragEnter, false);
        col.addEventListener("dragover", _this.handleDragOver, false);
        $(col).find(".story_board_row_drop_mask")[0].addEventListener("dragleave", _this.handleDragLeave, false);
        $(col).find(".story_board_row_drop_mask")[0].addEventListener("drop", _this.handleDrop, false);
        return col.addEventListener("dragend", _this.handleDragEnd, false);
      });
    }
  };

}).call(this);
