// Generated by CoffeeScript 1.7.1
(function() {
  window.JiraStoryTime.Templates.fetchAll(function() {
    var isStoryTime, renderStoryTime, setStoryTime;
    isStoryTime = function() {
      return window.JiraStoryTime.Util.deparam(location.href.split("?")[1])["story_time"] === "true";
    };
    setStoryTime = function(st) {
      var newUrl, params;
      params = window.JiraStoryTime.Util.deparam(location.href.split("?")[1]);
      params["story_time"] = st;
      newUrl = location.href.split("?")[0] + "?" + $.param(params);
      return history.pushState(null, null, newUrl);
    };
    renderStoryTime = function() {
      var possiblePoints;
      possiblePoints = [0, 1, 2, 3, 5, 8, 13, 21, window.JiraStoryTime.Story.NoPoints];
      if (!isStoryTime()) {
        setStoryTime(true);
      }
      return $.when(window.JiraStoryTime.Stories.fetchStories()).done(function() {
        var undefinedCol;
        $(document.body).append(window.JiraStoryTime.Templates.board);
        $(".overlay").focus();
        window.JiraStoryTime.Stories.addEpic("None");
        possiblePoints.forEach(function(points) {
          $("#story_board").append(window.JiraStoryTime.Templates.boardRow);
          $("#story_board")[0].lastChild.setAttribute("data-story-points", points);
          $("#story_board")[0].lastChild.setAttribute("id", "story-points-" + points);
          return $($("#story_board")[0].lastChild).find(".story_board_row_points").html(points);
        });
        undefinedCol = $($("#story_board")[0].lastChild);
        $.map(window.JiraStoryTime.Stories.backlog_stories, function(s) {
          return s.initialize(undefinedCol);
        });
        window.JiraStoryTime.DragController.setup();
        return $(".overlay").keyup(function(e) {
          if (e.keyCode === 27) {
            window.JiraStoryTime.Util.abortAllXHR();
            setStoryTime(false);
            $.map(window.JiraStoryTime.Stories.backlog_stories, function(s) {
              return s.close();
            });
            $(".overlay").off();
            $(".overlay").find("*").addBack().off();
            $(".overlay")[0].remove();
            return window.JiraStoryTime.Stories.epics = [];
          }
        });
      });
    };
    $("#ghx-modes").append(window.JiraStoryTime.Templates.storytoggle);
    $("#story-toggle").on("click", renderStoryTime);
    if (isStoryTime()) {
      return renderStoryTime();
    }
  });

}).call(this);
