// Generated by CoffeeScript 1.7.1
(function() {
  var Templates;

  window.JiraStoryTime = window.JiraStoryTime || {};

  window.JiraStoryTime.Templates = Templates = (function() {
    function Templates() {}

    Templates.templates = ["board", "storytoggle", "boardRow", "boardStory", "boardEpic"];

    Templates.fetchAll = function(OnDone) {
      var counter;
      counter = 0;
      return this.templates.forEach((function(_this) {
        return function(file_name, i) {
          return $.ajax({
            url: chrome.extension.getURL("/src/templates/" + file_name + ".html"),
            context: document.body
          }).done(function(response) {
            _this[file_name] = response;
            counter = counter + 1;
            if (counter === _this.templates.length) {
              return OnDone();
            }
          });
        };
      })(this));
    };

    return Templates;

  })();

}).call(this);
