// Generated by CoffeeScript 1.7.1
(function() {
  window.JiraStoryTime = window.JiraStoryTime || {};

  window.JiraStoryTime.Util = {
    deparam: function(query) {
      var i, key, keyValuePair, map, pairs, value;
      pairs = void 0;
      i = void 0;
      keyValuePair = void 0;
      key = void 0;
      value = void 0;
      map = {};
      if (query.slice(0, 1) === "?") {
        query = query.slice(1);
      }
      if (query !== "") {
        pairs = query.split("&");
        i = 0;
        while (i < pairs.length) {
          keyValuePair = pairs[i].split("=");
          key = decodeURIComponent(keyValuePair[0]);
          value = (keyValuePair.length > 1 ? decodeURIComponent(keyValuePair[1]) : undefined);
          map[key] = value;
          i += 1;
        }
      }
      return map;
    },
    xhrPool: [],
    abortAllXHR: function() {
      window.JiraStoryTime.Util.xhrPool.forEach(function(jqXHR) {
        jqXHR.abort();
      });
      window.JiraStoryTime.Util.xhrPool.length = 0;
    }
  };

  $.ajaxSetup({
    beforeSend: function(jqXHR) {
      window.JiraStoryTime.Util.xhrPool.push(jqXHR);
    },
    complete: function(jqXHR) {
      var index;
      index = window.JiraStoryTime.Util.xhrPool.indexOf(jqXHR);
      if (index > -1) {
        window.JiraStoryTime.Util.xhrPool.splice(index, 1);
      }
    }
  });

}).call(this);
